[input]
base_directory = "data"
url_prefix = "/"
frontmatter_handling = "Omit"

  [[input.files]]
  path = "articles/post-01.mdx"
  url = "articles/post-01"
  title = "Soft Shell Crab Salad + Fish"
  filetype = "Markdown"

  [[input.files]]
  path = "articles/post-02.mdx"
  url = "articles/post-02"
  title = "Thai Beef Salad"
  filetype = "Markdown"

  [[input.files]]
  path = "articles/post-03.mdx"
  url = "articles/post-03"
  title = "Jungle Curry"
  filetype = "Markdown"
